### ISSUE TITLE
Won't talk

### ISSUE THREAD

**Issue by Phantommmmm** [Gnome-py/Discord-TTS-Bot#54]
Sometimes the bot will connect to the channel but won't talk.

**Comment by Gnome-py** [comment]
Yeah... This happens during a gtts block during espeak mode. For some reason the ProcessPoolExecutor gets stuck and won't call make_espeak anymore, stalling the bot.
If anyone has an idea of why this happens let me know, I'm thinking of moving espeak to a different process and using docker-compose to handle IPC and stuff, which should fix this issue (or at least make it more diagnosable)

**Comment by Phantommmmm** [comment]
Is there any way to at least reset the bot?, maybe the good ol' resetting is a workaround lol

**Comment by Phantommmmm** [comment]
Fair enough, if it is of any help this is what happened.

- Use the bot for a bit.
- Don't use it for a while.
- After noticing the bot, disconnecting it using discord's tool (not by -leave)
- Use it again.

**Comment by Gnome-py** [comment]
Just saying, the block is global and the bot tries again with Google every hour, I also get log messages every time the bot swaps between modes and it doesn't require a leave/join.
