### ISSUE TITLE
[Feature Request] Make different voices for different users possible

### ISSUE THREAD

**Issue by xHadie** [Gnome-py/Discord-TTS-Bot#56]
Currently, it is not easy to discriminate who is talking, when multiple people use the bot (for example while playing a game in fullscreen mode).

Supporting multiple voices (either pre-defined or generated) would mitigate this issue.

I'd like to propose following two implementation strategies:

### Choose voice by prefix-addon
Adding an option to allow people to use a custom prefix like `'1`,` '2`, etc. to select one of various pre-defined voices for their message.

While this solution seems easy and fast to implement, the altercation of the prefix feels a bit messy.. 

### Store user-based preferences
The idea is to allow users to change settings of the voice they are using (type, pitch, speed, etc ?) by using a command.
This would require to store the settings in some sort of database. A user-related save file is probably more than sufficient though 😄.

I just skimmed through the repository, but didn't find some sort of user-related storage? Setting up a pipeline for this could open up the door for many interesting personlization features, that would make the usage of the bot much more fun!

I am experienced with pydub and librosa, so I might be able to help with the implementation of this feature if you agree with it's implementation!

**Comment by Redst0neFlux** [comment]
use -voices
then -set voice <voice>

**Comment by Gnome-py** [comment]
My first concern here is CPU usage, as playing with audio like that could get expensive at scale (TTS Bot does around 50k messages per day), we do have a user settings table in the database to store the current TTS language and DM block status (take a look at `extensions/database_handler.py` and the schema in `utils/constants.py`) so this wouldn't be too hard to implement, it's just speed that I am worried about.

Please contact me via Discord via `Gnome!#6669` so we can chat further!
