### ISSUE TITLE
can't import from signal?

### ISSUE THREAD

**Issue by Phantommmmm** [Gnome-py/Discord-TTS-Bot#62]
Good afternoon, got this error while trying to self-host on python
```
>D:\DiscordTTS> python3 main.py
Traceback (most recent call last):
  File "D:\DiscordTTS\main.py", line 8, in <module>
    from signal import SIGHUP, SIGINT, SIGTERM
ImportError: cannot import name 'SIGHUP' from 'signal' (C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\signal.py)
```

Tried to pip signal but didn't find anything, hope you can help with anything.

**Comment by Gnome-py** [comment]
This is an OS specific difference, currently TTS Bot only supports Linux with python 3.9, if you want to run it on Linux use docker or WSL.
