### ISSUE TITLE
Error from daemon

### ISSUE THREAD

**Issue by Phantommmmm** [Gnome-py/Discord-TTS-Bot#63]
Hello again, after using docker-compose build with no errors at all and trying to run docker-compose up I get this weird error

`Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/run/desktop/mnt/host/d/DiscordTTS/keydb.conf" to rootfs at "/etc/keydb/keydb.conf" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

I have tried searching on the internet, as my first thought was that my Docker instalation was faulty, but it seems it's about something with the filesystem. My knowledge with Docker is miniscule as this may be the 3rd project I have in there.
Docker Logs:
<details>
 <summary>Container Logs:</summary>
        
![image](https://user-images.githubusercontent.com/52291631/131225255-c6aef632-c083-445d-be62-e2bc5b11bf1d.png)

</details>
<details>
 <summary>Bot image on docker:</summary>
        
![image](https://user-images.githubusercontent.com/52291631/131225338-0feb04d9-eb61-4589-bc0c-a59256e8f156.png)

</details>

</details>
<details>
 <summary>postgresql image on docker:</summary>
        
![image](https://user-images.githubusercontent.com/52291631/131225350-ffca61aa-f933-4e21-9137-22169e971686.png)

</details>

</details>

Appreciations in advance.

**Comment by Gnome-py** [comment]
Create a file called keydb.conf and preferably fill it with the defaults from https://docs.keydb.dev/docs/config-file/ (with `Configuring KeyDB as a cache`). Please contact me via Discord as `Gnome!#6669` for further help in setting up TTS Bot.
